[package]
edition = "2018"
name = "onefetch"
description = "Git repository summary on your terminal"
version = "2.9.0"
authors = ["o2sh <ossama-hjaji@live.fr>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/o2sh/onefetch"
exclude = ["assets/*", "tools/*"]

[package.metadata.deb]
maintainer = "o2sh <ossama-hjaji@live.fr>"
extended-description = """\
Onefetch is a command-line Git information tool written in Rust \
that displays project information and code statistics \
for a local Git repository directly on your terminal."""
depends = "$auto"
section = "utility"
priority = "optional"

[dependencies]
color_quant = "1.1" # Use version required by image
colored= "2.0.0"
git2 = { version = "0.13.15", default-features = false }
json = "0.12.4"
tokei = "12.1.2"
askalono = "0.4.3"
bytecount = "0.6.2"
clap = "2.33.3"
strum = { version = "0.20.0", features = ["derive"] }
term_size = "0.3.2"
image = "0.23.12"
regex = "1"
error-chain = "0.12"
toml = "0.5.8"
yaml-rust = "0.4"
serde = "1.0.118"
serde_json = "1.0.93"
serde_yaml = "0.8"

chrono = "0.4"
chrono-humanize = "0.1.1"
byte-unit = "4.0.9"

[target.'cfg(windows)'.dependencies]
ansi_term = "0.12"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2.82"
base64 = "0.13.0"

[dev-dependencies]
more-asserts = "0.2"
paste = "1"

[features]
fail-on-deprecated = []
